import random

cardStack = {
    'Golden Signals': 'Latency\nTraffic\nError Rates\nSaturation',
    '3 Pillars of Observability': 'Logs\nMetrics\nTraces',
    'Latency': 'Time it takes for a request to travel from the client to the server and back\nOne of the observability golden signals',
    'Traffic': 'Number of requests a system receives over a specific period\nMeasured in requests per second (RPS), transactions per second (TPS), or bits per second (bps)\nOne of the observability golden signals',
    'Errors (Monitoring)': 'Percentage of requests resulting in errors, such as 404 Page Not Found or 500 Internal Server errors\nOne of the observability golden signals',
    'Saturation': 'Measures resource utilization, including CPU, memory and disk space\nOne of the observability golden signals',
    'VPC': 'Virtual Private Cloud\nIsolated virtual network in AWS\nYou define IP address range, subnets, route tables, and gateways',
    'VPN': 'Virtual Private Network\nSecure connection over public network\nEncrypts data in transit\nCommonly used to connect on-premises networks to cloud resources',
    'Traceroute': 'Network diagnostic tool\nDisplays path packets take from source to destination\nShows each hop along the route and time taken for each hop\nHelps identify network issues and latency',
    'Subnet': 'CIDR block portion of a VPC\nLives in Availability Zones\nPublic: Has route to Internet Gateway\nPrivate: Does not have route to Internet Gateway',
    'IGW': 'Internet Gateway\nAllows communication between VPC and internet\nAttached to VPC\nRoute table must have route to IGW for public subnet',
    'SG': 'Security Group\nStateful\nOperates at instance level\nSupports allow rules only\nEvaluated after NACLs',
    'EC2': 'Elastic Compute Cloud\nVirtual servers in the cloud\nProvides resizable compute capacity\nSupports various instance types optimized for different use cases',
    'EBS': 'Elastic Block Store\nBlock-level storage volumes for use with EC2 instances\nProvides persistent storage that can be attached to and detached from instances\nSupports various volume types optimized for different performance and cost requirements',
    'RDS': 'Relational Database Service\nManaged relational database service\nSupports multiple database engines (MySQL, PostgreSQL, Oracle, SQL Server, etc.)\nHandles database administration tasks such as backups, patching, and scaling',
    'KMS': 'Key Management Service\nManaged service for creating and controlling encryption keys\nEnables secure encryption of data at rest and in transit\nIntegrates with other AWS services for seamless encryption management',
    'IAM': 'Identity and Access Management\nManages access to AWS services and resources securely\nEnables creation of users, groups, and roles with specific permissions\nSupports multi-factor authentication (MFA) for enhanced security',
    'Secrets Manager': 'Service for securely storing and managing sensitive information such as database credentials, API keys, and other secrets\nProvides automatic rotation, secure access, and auditing capabilities\nIntegrates with AWS services and applications for seamless secret management',
    'Well-Architected Framework': 'Operational Excellence\nSecurity\nReliability\nPerformance Efficiency\nCost Optimization',
    'Fault Tolerance': 'Ability of a system to continue operating properly in the event of the failure of some of its components\nAchieved through redundancy, failover mechanisms, and distributed architectures\nMinimizes downtime and ensures high availability',
    'High Availability': 'Designing systems to be operational and accessible for a high percentage of time\nAchieved through redundancy, failover mechanisms, and distributed architectures\nMinimizes downtime and ensures continuous access to services',
    'Blue/Green Deployment': 'Deployment strategy that reduces downtime and risk by running two identical production environments (Blue and Green)\nTraffic is routed to the Blue environment while the Green environment is updated\nOnce the Green environment is verified, traffic is switched to it, making it the new production environment',
    'Canary Deployment': 'Deployment strategy that gradually rolls out changes to a small subset of users before deploying to the entire user base\nAllows for monitoring and validation of changes in a controlled manner\nHelps identify issues early and minimizes the impact of potential failures',
    'Auto Scaling Group': 'Collection of EC2 instances treated as a logical grouping for automatic scaling and management\nEnsures the desired number of instances are running based on defined policies\nSupports scaling in and out based on demand',
    'CI/CD': 'Continuous Integration/Continuous Deployment\nPractices for automating the build, testing, and deployment of applications\nEnables faster and more reliable software delivery\nCommon tools: AWS CodePipeline, Jenkins, GitLab CI/CD',
    'IaC': 'Infrastructure as Code\nPractice of managing and provisioning infrastructure using code and automation tools\nEnables version control, repeatable deployments, and easier management of complex infrastructures\nCommon tools: AWS CloudFormation, Terraform, Ansible',
    'GitOps': 'Operational model that uses Git as the single source of truth for infrastructure and application code\nEnables collaboration, version control, and automated deployments\nIntegrates with CI/CD pipelines for continuous delivery',
    'RESTful API': 'Stateless\nClient-server architecture\nCacheable responses\nUniform interface\nLayered system\nCode on demand (optional)',
    'Disaster Recovery': 'Strategies to recover from catastrophic failures\nBackup and Restore\nPilot Light\nWarm Standby\nMulti-Site',
    'Lifecycle Hook': 'Feature of Auto Scaling Groups that allows you to perform custom actions when instances launch or terminate\nEnables you to pause the instance lifecycle to perform tasks such as configuration, software installation, or data backup before the instance becomes available or is terminated',
    'Lifecycle Policy': 'Defines the actions to be taken during the lifecycle of an Auto Scaling Group instance\nSpecifies the conditions under which instances are launched or terminated\nCan include scaling policies, health checks, and instance refresh settings',
    'Route Table': 'Set of rules (routes) that determine where network traffic is directed\nAssociated with subnets in a VPC\nContains routes to local VPC, IGW, NAT Gateway, peered VPCs, etc.',
    'NAT Gateway': 'Network Address Translation Gateway\nEnables instances in a private subnet to connect to the internet or other AWS services\nPrevents inbound traffic from the internet to those instances\nRequires an Elastic IP address',
    'S3 Endpoint': 'Enables private connections between a VPC and S3 without using an internet gateway, NAT device, VPN connection, or AWS Direct Connect\nTraffic between the VPC and S3 does not leave the Amazon network\nImproves security and reduces data transfer costs',
    'NACL': 'Network Access Control List\nStateless\nOperates at subnet level\nSupports allow and deny rules\nEvaluated before security groups',
    'ALB': 'Application Load Balancer\nDistributes incoming network traffic across multiple targets (webservers or containers) based on the content of the application-level requests\nOperates at 7th layer of OSI model\nCan inspect HTTP(S) request data',
    'AMI': 'Amazon Machine Image\nPreconfigured template required to launch EC2\nIncludes OS, software packages, custom files\nUsed by autoscaling and disaster recovery',
    'Route 53': 'DNS lookup\nProvide IP address associated with domain name\nCan point to CloudFront, S3, Load Balancer, EC2, Static IP\nCan be used to register domains',
    'AWS Physical and Networking Layers': 'Regions, Availability Zones, Edge Locations',
    'Region': 'General geographic area for AWS physical and networking resources\nExamples: us-east-1, eu-central-1',
    'Availability Zone': 'Isolated datacenters within regions\nExamples: us-east-1a, 1b, 1c, 1d',
    'Edge Location': 'Smaller datacenters in most cities\nUsed by Route53 and CloudFront to cache content close to endusers for better performance',
    'Horizontal Scaling': 'Increase compute capacity by increasing number of instances',
    'Vertical Scaling': 'Increase compute capacity by migrating to larger instances',
    'CloudFront': 'Content Delivery Network (CDN)\nCaches copies of static content at Edge Locations globally\nReduces latency by serving content from nearest edge location to user',
    'CloudFormation': 'Infrastructure as Code (IaC)\nAutomates provisioning and management of AWS resources using templates\nEnables version control, repeatable deployments, and easier management of complex infrastructures',
    'EMR': 'Elastic Map Reduce\nManaged Hadoop framework\nProcesses large datasets across resizable clusters of EC2 instances\nUsed for big data analytics, machine learning, and data processing tasks',
    'SSH Key Pair': 'Authentication method for securely accessing EC2 instances\nConsists of a public key (stored on the instance) and a private key (held by the user)\nUsed to establish encrypted SSH connections to Linux instances',
    'Lambda': 'Serverless compute service\nRuns code in response to events without provisioning or managing servers\nAutomatically scales based on demand\nSupports multiple programming languages',
    'SQS': 'Simple Queue Service\nFully managed message queuing service\nEnables decoupling and scaling of microservices, distributed systems, and serverless applications\nSupports standard and FIFO queues',
    'SNS': 'Simple Notification Service\nFully managed publish/subscribe messaging service\nEnables decoupling of microservices, distributed systems, and serverless applications\nSupports multiple protocols including HTTP/S, email, SMS, and Lambda functions',
    'Message Queue': 'Communication method between distributed components\nStores messages until they are processed and deleted by the consumer\nEnables asynchronous communication and decoupling of components',
    'FIFO': 'First In, First Out\nMessage processing order where the first message sent to the queue is the first one to be received and processed\nEnsures strict ordering of messages\nCommonly used in scenarios where the order of operations is critical',
    'FILO': 'First In, Last Out\nMessage processing order where the first message sent to the queue is the last one to be received and processed\nLess common than FIFO\nUsed in specific scenarios where reverse order processing is required',
    'Short Polling': 'Method of retrieving messages from an SQS queue where the consumer makes a request to the queue and immediately receives any available messages\nIf no messages are available, the request returns an empty response\nCan result in higher latency and increased costs due to frequent polling',
    'Long Polling': 'Method of retrieving messages from an SQS queue where the consumer makes a request to the queue and waits for a specified duration (up to 20 seconds) for messages to become available\nReduces latency and costs by minimizing the number of empty responses\nImproves efficiency of message retrieval',
    'STS': 'Security Token Service\nWeb service that enables you to request temporary, limited-privilege credentials for AWS Identity and Access Management (IAM) users or for users that you authenticate (federated users)\nUseful for granting access to AWS resources without sharing long-term credentials',
    'Federation': 'Process of allowing users from an external identity provider (IdP) to access AWS resources without creating separate IAM users\nUses standards like SAML, OIDC, or OAuth\nEnables single sign-on (SSO) and centralized user management',
    'Headless User': 'IAM user without console access\nUsed for programmatic access to AWS resources via APIs, CLI, or SDKs\nTypically associated with applications, services, or automation scripts',
    'Evenutal Consistency': 'Data replication model where updates to a data store may not be immediately visible to all read operations\nOver time, all replicas will converge to the same state\nCommon in distributed systems to improve performance and availability (ex: S3)',
    'Strong Consistency': 'Data replication model where updates to a data store are immediately visible to all read operations\nEnsures that all replicas reflect the most recent write\nProvides the highest level of data consistency but may impact performance and availability (ex: RDS)',
    'Intelligent Tiering': 'S3 storage class that automatically moves data between two access tiers (frequent and infrequent) based on changing access patterns\nOptimizes storage costs by ensuring data is stored in the most cost-effective tier without performance impact\nIdeal for data with unknown or changing access patterns',
    'VPC Peering': 'Networking connection between two VPCs that enables routing of traffic between them using private IP addresses\nCan be established within the same AWS account or across different AWS accounts\nDoes not require a gateway, VPN connection, or separate network appliance',
    'ECS': 'Elastic Container Service\nFully managed container orchestration service\nSupports Docker containers\nEnables easy deployment, management, and scaling of containerized applications\nIntegrates with other AWS services like IAM, VPC, and CloudWatch',
    'EKS': 'Elastic Kubernetes Service\nFully managed Kubernetes service\nSimplifies deployment, management, and scaling of containerized applications using Kubernetes\nHandles tasks like cluster provisioning, patching, and scaling\nIntegrates with other AWS services for security, networking, and monitoring',
    'CloudWatch': 'Monitoring and observability service\nCollects and tracks metrics, logs, and events from AWS resources and applications\nProvides dashboards, alarms, and automated actions based on defined thresholds\nHelps gain insights into system performance and operational health',
    'DogStatsD': 'A statsd-compatible daemon for aggregating statistics, such as counters and timers, sent over UDP or TCP and sending aggregates to one or more pluggable backend services\nOften used for application performance monitoring and metrics collection',
    'StatsD': 'A network daemon that listens for statistics, like counters and timers, sent over UDP or TCP and sends aggregates to one or more pluggable backend services\nCommonly used for application performance monitoring and metrics collection',
    'OpenTelemetry': 'An open-source observability framework for cloud-native software\nProvides APIs, libraries, agents, and instrumentation to collect metrics, logs, and traces from applications and infrastructure\nSupports multiple programming languages and integrates with various backend systems for analysis and visualization',
    'Prometheus': 'An open-source systems monitoring and alerting toolkit\nCollects and stores metrics as time series data\nProvides a powerful query language (PromQL) for querying and analyzing metrics\nOften used in conjunction with Grafana for visualization',
    'Grafana': 'An open-source platform for monitoring and observability\nProvides tools for visualizing time series data from various data sources, including Prometheus, InfluxDB, and Elasticsearch\nEnables the creation of customizable dashboards and alerts for monitoring system performance and health',
    'ELK Stack': 'Elasticsearch, Logstash, and Kibana\nA popular open-source stack for log management and analysis\nElasticsearch: Search and analytics engine\nLogstash: Data processing pipeline for collecting, parsing, and storing logs\nKibana: Visualization tool for exploring and analyzing log data',
    'Kibana': 'A data visualization and exploration tool\nPart of the ELK Stack (Elasticsearch, Logstash, Kibana)\nProvides a web interface for creating dashboards and visualizations based on data stored in Elasticsearch\nUsed for log analysis, monitoring, and reporting',
    'Datadog HTTP API': 'A RESTful API provided by Datadog that allows users to programmatically send metrics, events, and service checks to their Datadog account\nEnables integration with custom applications and services for monitoring and observability purposes',
    'Elasticsearch': 'A distributed, RESTful search and analytics engine\nPart of the ELK Stack (Elasticsearch, Logstash, Kibana)\nStores and indexes large volumes of data for fast search and analysis\nCommonly used for log and event data analysis, full-text search, and real-time analytics',
    'Logstash': 'A server-side data processing pipeline\nPart of the ELK Stack (Elasticsearch, Logstash, Kibana)\nCollects, parses, and transforms log and event data from various sources\nSends processed data to Elasticsearch for storage and analysis',
    'Datadog Agent': 'A lightweight software that runs on your hosts to collect metrics, traces, and logs from your applications and infrastructure\nSends the collected data to the Datadog platform for monitoring, analysis, and visualization\nSupports a wide range of integrations with popular technologies and services',
    'IAM Role': 'An IAM entity that defines a set of permissions for making AWS service requests\nCan be assumed by trusted entities such as AWS services, applications, or users\nUsed to grant temporary access to AWS resources without sharing long-term credentials',
    'IAM Policy': 'A JSON document that defines permissions for an IAM user, group, or role\nSpecifies allowed or denied actions on AWS resources\nCan be managed (predefined by AWS) or customer-managed (created by users)\nUsed to control access to AWS services and resources',
    'CloudTrail': 'AWS service that enables governance, compliance, operational auditing, and risk auditing of your AWS account\nRecords AWS API calls and events for your account and delivers log files to an S3 bucket\nHelps track changes to AWS resources and monitor user activity',
    'VPC Flow Logs': 'Feature that enables you to capture information about the IP traffic going to and from network interfaces in your VPC\nFlow log data can be published to Amazon CloudWatch Logs or Amazon S3\nUseful for monitoring network traffic, troubleshooting connectivity issues, and enhancing security analysis',
    'Observability': 'Ability to measure the internal states of a system by examining its outputs\nAchieved through collecting and analyzing logs, metrics, and traces\nHelps understand system behavior, diagnose issues, and improve performance',
    'O11y': 'Abbreviation for Observability\nRefers to the practice of measuring and understanding the internal states of a system through its outputs\nInvolves collecting and analyzing logs, metrics, and traces to gain insights into system behavior and performance',
    'Observability vs. Monitoring': 'Monitoring: Focuses on collecting predefined metrics and logs to track system health and performance\nObservability: Encompasses monitoring but also includes the ability to explore and analyze data to understand system behavior and diagnose issues\nObservability provides deeper insights into complex systems compared to traditional monitoring',
    'APM': 'Application Performance Monitoring\nTools and practices for monitoring and managing the performance and availability of software applications\nInvolves collecting metrics, traces, and logs to gain insights into application behavior and user experience\nHelps identify and resolve performance bottlenecks and issues',
    'APM Trace': 'A record of the journey of a single request as it travels through various services and components of a distributed system\nIncludes information about each operation performed, timing, and any errors encountered\nHelps visualize and analyze the performance and behavior of applications',
    'Data Warehouse': 'Centralized repository for storing and managing large volumes of structured data from multiple sources\nOptimized for query and analysis rather than transaction processing\nSupports business intelligence, reporting, and data analytics',
    'Data Lake': 'Centralized repository for storing large volumes of raw and unstructured data\nAllows storage of data in its native format until needed for analysis\nSupports diverse data types and sources',
    'SLA': 'Service Level Agreement\nFormal contract between a service provider and a customer\nDefines the expected level of service, performance metrics, and responsibilities\nIncludes penalties or remedies for failing to meet agreed-upon service levels',
    'Data Lineage': 'Tracking the origin, movement, and transformation of data throughout its lifecycle\nProvides visibility into data sources, processing steps, and destinations\nHelps ensure data quality, compliance, and governance',
    'OpenTelemetry Collector': 'A component of the OpenTelemetry framework that collects, processes, and exports telemetry data (metrics, logs, traces) from applications and infrastructure\nSupports various data sources and exporters for integration with backend systems\nEnables centralized management of telemetry data collection and processing',
    'OpenTelemetry SDK': 'A set of libraries and APIs provided by the OpenTelemetry framework for instrumenting applications to collect telemetry data (metrics, logs, traces)\nSupports multiple programming languages\nEnables developers to add observability capabilities to their applications easily',
    'OpenTelemetry Agent': 'A lightweight component of the OpenTelemetry framework that runs alongside applications to collect telemetry data (metrics, logs, traces)\nSends collected data to the OpenTelemetry Collector or directly to backend systems\nFacilitates the instrumentation of applications for observability purposes',
    'SaaS architecture': 'Software as a Service\nCloud computing model where applications are hosted by a service provider and made available to users over the internet\nEliminates the need for users to install and maintain software on their local devices\nExamples: Google Workspace, Salesforce, Dropbox'
}


o11yStack = {
    "AAL": "Admin Activity Log - similar to the CAL it is just for administrator only activities",
    "ADR": "Architect Decision Record - A document that describes a choice the team makes about a significant aspect of the software architecture they're planning to build. Each ADR describes the architectural decision, its context, and its consequences. ADRs have states and therefore follow a lifecycle",
    "APM": "Application Performance Monitoring - software tools and practices to track, diagnose, and optimize how software applications perform, providing deep visibility into user experience, code execution, and infrastructure to ensure speed, availability, and reliability by pinpointing bottlenecks and errors across the full stack. It collects data like response times, error rates, and resource usage, often using lightweight agents and transaction tracing to map user requests from front-end to back-end services, helping teams resolve issues faster and improve overall application health",
    "AppDynamics": "an Application Performance Monitoring (APM) tool - it's a competitor to Datadog APM. It monitors application performance, user experience, and business metrics in real-time.",
    "Assertion": "in Datadog, defines what an expected test result is",
    "AWS Service Catalog": "a governance service letting organizations create and manage catalogs of approved, pre-configured IT services (like CloudFormation/Terraform templates) for users to self-provision, ensuring compliance, security, and cost control through centralized management and constraints, acting like an internal marketplace for standardized cloud resources",
    "BFF": "Backend For Frontend - a dedicated backend service built for a specific frontend application (like web, iOS, or Android) to optimize its unique needs, aggregating data from core microservices and returning exactly what that client needs, simplifying development and improving performance, security, and user experience for each platform. Instead of one generic API for all clients, you have tailored backends, ensuring each interface (web, mobile, TV) gets a perfectly tuned experience",
    "CAB": "Change Advisory Board - Change management meeting every Tuesday at 9am",
    "CAL": "Consolidated Activity Log - a set of files that get written to every time users take certain actions in the system.  They are horrible because they are a contention point for the servers.  There is an alert setup in AppDynamics that whenever it takes more than 100ms to write to the file in a 5 minute period an alert is sent.",
    "ClearScale": "Consulting firm that Ken and others work for",
    "ClickOps": "Snarky term for resources in AWS built by clicking in the console, not IaC'd and usually improperly tagged.",
    "CloudZero": "3rd-party cost visibility and reporting service. Anomaly detection.",
    "Continuous Profiler": "analyzes the performance of your entire code base, in any environment, all the time and with negligible overhead. Quickly identify and optimize the slowest and most resource-intensive services, endpoints, and lines of code to resolve issues faster, reduce application latency, and lower cloud costs.",
    "Couchbase": "a high-performance, distributed NoSQL database that combines in-memory speed with flexible JSON document storage",
    "DirectConnect": "creates a private, dedicated network link between your on-premises data center or office and a cloud provider, bypassing the public internet for better security, lower latency, and consistent performance, essential for hybrid cloud setups and meeting compliance needs",
    "DSM": "Data Streams Monitoring - A specific feature in tools like Datadog that tracks event flow in message queues (Kafka, RabbitMQ) to find bottlenecks.",
    "EventBus": "a central communication channel that routes events (notifications of something happening) from various sources (publishers) to interested destinations (subscribers or targets) in an event-driven architecture, promoting loose coupling by decoupling producers from consumers, allowing systems to scale and handle real-time data efficiently, with examples like AWS EventBridge offering default and custom buses for cloud services and applications.",
    "Fargate": "a serverless compute engine for containers that works with Amazon ECS (Elastic Container Service) and EKS (Elastic Kubernetes Service), letting you run Docker containers without managing servers or clusters; it handles infrastructure provisioning and scaling automatically, so you just define your container's CPU/memory needs and Fargate runs it, offering cost-effectiveness, security (per-task isolation), and integration with other AWS services.",
    "FedRAMP": "Federal Risk and Authorization Management Program - U.S. government-wide initiative standardizing security for cloud services, ensuring they meet strict security controls (based on NIST standards) before federal agencies can use them.",
    "FinOps": "cloud financial management discipline that combines finance and DevOps to optimize cloud spending and maximize its business value. It is a cultural practice that promotes collaboration between technology, finance, and business teams to foster shared responsibility, visibility, and accountability for cloud costs. The goal is to make data-driven spending decisions that align cloud investments with business objectives.",
    "Fluent Bit": "a high-performance, lightweight log, metrics, and trace processor/forwarder designed for collecting data from various sources, processing it efficiently with plugins, and routing it to destinations like Elasticsearch, Splunk, or Kafka, making it ideal for cloud-native environments like Kubernetes due to its low resource usage. It acts as a central data pipeline, reducing complexity and cost in observability setups.",
    "IDP": "Brandon Rock's team",
    "Indexed Span": "a specific operation (a \"span\") within application performance monitoring (APM) that has its metadata (tags/attributes like status_code, db.name, job_id) \"indexed\" by an observability platform (like Datadog or Splunk APM) to enable powerful, detailed analysis and filtering, moving beyond just viewing whole traces to breaking down performance by specific attributes. Instead of just seeing a trace, indexing lets you group and analyze metrics for all spans sharing a specific tag value, crucial for troubleshooting and understanding service behavior.",
    "Input Set": "collections of pipeline settings and parameters that are passed into a pipeline at runtime",
    "ISS": "Internet Information Services - Azure virtual machine, essentially the equivalent of an EC2",
    "JWT": "JSON Web Token - a compact, secure way to transmit information as a JSON object between parties, commonly used for user authentication and authorization in web apps, enabling stateless sessions where the server verifies the token's signature instead of storing session data. It consists of three parts (Header, Payload, Signature) separated by dots, each Base64-URL encoded, ensuring integrity and trust by cryptographically signing the data, making it ideal for APIs, microservices, and Single Sign-On (SSO)",
    "KTLO": "Keep The Lights On - EOL systems that are still maintained",
    "Landing Zone": "a well-architected, multi-account AWS environment that is scalable and secure. This is a starting point from which your organization can quickly launch and deploy workloads and applications with confidence in your security and infrastructure environment. Building a landing zone involves technical and business decisions to be made across account structure, networking, security, and access management in accordance with your organization's growth and business goals for the future.",
    "Megaport": "a global Network as a Service (NaaS) provider that uses software-defined networking (SDN) to offer private, on-demand, and scalable connectivity between businesses, cloud providers (like AWS, Azure, Google Cloud), data centers, and other services, simplifying hybrid and multi-cloud environments",
    "ND Zone": "Geographic and Environmental zone.  Ex:  us-dev, ca-prod",
    ".NET8": "Microsoft's Long-Term Support (LTS) release of its cross-platform, open-source developer platform, offering significant performance boosts",
    "NoBS": "nobs.tech, DataDog expert services, partner firm for consulting",
    "Non-Deterministic": "a system or algorithm can produce different outputs or take different paths with the same input, unlike deterministic systems that always yield the same result, often due to inherent randomness, parallel processing, or choices between possibilities",
    "Nutanix": "a cloud computing company known for its Hyperconverged Infrastructure (HCI) platform, which unifies compute, storage, and virtualization into a single, software-defined stack for simplified management and hybrid/multi-cloud operations",
    "Octopus Deploy": "a continuous delivery (CD) and deployment automation tool that helps software teams release and deploy applications reliably and consistently across various environments, from on-premises servers to multi-cloud (AWS, Azure, Google Cloud) and Kubernetes. It automates complex release processes, manages configurations, handles infrastructure changes, and provides visibility into deployments, enabling teams to achieve faster, more repeatable software delivery with features like multi-tenancy and runbooks for operational tasks.",
    "OSM": "Object Store Migration",
    "OU": "Organizational Unit",
    "RCP": "Resource Control Policy - A type of organization policy that you can use to manage permissions in your organization. RCPs offer central control over the maximum available permissions for resources in your organization. RCPs help you to ensure resources in your accounts stay within your organization's access control guidelines.  Controls WHICH principals can access SPECIFIC RESOURCES.  Scope: resource level",
    "Redis": "REmote DIctionary Server - a super-fast, open-source, in-memory data store used as a database, cache, and message broker",
    "RUM": "Real User Monitoring - Tracks actual user interactions with web/mobile apps to provide end-to-end visibility into their experience, measuring performance (page loads, actions), errors, and usage patterns (location, device) by embedding lightweight scripts/SDKs to collect real-time data, correlating it with backend metrics for full-stack observability and proactive troubleshooting",
    "SAML": "Security Assertion Markup Language - an open standard protocol for exchanging authentication and authorization data between an Identity Provider (IdP) and a Service Provider (SP), enabling Single Sign-On (SSO), where users log in once to access multiple applications securely",
    "Semantic Search": "an information retrieval method that uses AI, Natural Language Processing (NLP), and machine learning to understand the intent and contextual meaning behind a user's query, rather than just matching keywords, to deliver more relevant, human-like results by grasping relationships between words and concepts, often using vector embeddings and knowledge graphs",
    "Semver": "Semantic verisioning - A formal convention for assigning version numbers to software to communicate the nature of changes. It uses a three-part version number, MAJOR.MINOR.PATCH, where an increment in each part signifies a specific type of change: MAJOR for breaking changes, MINOR for new backward-compatible features, and PATCH for backward-compatible bug fixes.",
    "SCP": "Service Control Policies - Enforce account-level restrictions, controls WHO can do WHAT.  Scope: account level",
    "Sidecar": "an additional container that runs alongside your main application container within the same task or pod, e.g. running the DataDog agent",
    "Snowflake": "cloud-based data platform (Data Cloud) that allows companies to store, process, and analyze massive amounts of data efficiently, acting as a modern data warehouse by separating storage and compute for independent scaling. It's a fully managed service (SaaS) that simplifies data management, enabling secure data sharing and supporting various workloads, from traditional analytics to AI/ML, across major cloud providers like AWS, Azure, and GCP.",
    "Solr": "open-source, standalone enterprise search platform that provides powerful full-text, real-time search, analytics, and indexing capabilities built on top of the Apache Lucene library",
    "Span": "the fundamental building block of Distributed Tracing, representing a single unit of work or operation (like a database query, HTTP call, or function execution) within a larger request. Spans contain metadata like start/end times, operation names, tags (attributes, host info), and can link to other spans, forming a hierarchical Trace, which provides a complete picture of a request's journey across different services in a distributed system.",
    "Synthetics": "automated scripts and bots to simulate user journeys and transactions.  Identify performance issues by simulating user journeys.  Proactively monitors service availability, application response times and customer transaction functionality.",
    "Synthetic observability": "the proactive practice of simulating user interactions with applications, APIs, and websites to measure performance, availability, and user experience from various global locations and devices, detecting issues before real users encounter them. It uses scripted tests to emulate workflows (like login, checkout), offering consistent, repeatable data for monitoring and troubleshooting.",
    "Target Groups": "a logical grouping of backend resources (like EC2 instances, IP addresses, or Lambda functions) that your load balancer forwards traffic to, acting as the destination for requests after the listener rules are met, with per-group health checks to ensure traffic only goes to healthy servers. It's the crucial bridge between the load balancer's incoming traffic and your application's compute resources, defining what receives the traffic and how they are checked for health",
    "Telemetry": "the automated collection, transmission, and analysis of data (metrics, logs, traces) from applications and infrastructure to provide real-time insights into system behavior, performance, and user activity, enabling proactive monitoring, faster troubleshooting, and continuous improvement. It's the foundation of observability, giving teams deep visibility into production systems to understand \"what's happening\" without needing to manually check or debug every component",
    "Trace": "detailed, end-to-end records of a single user request's journey as it travels through a complex, distributed system, showing each service it touches, how long each step takes (spans), and the interactions between components, helping pinpoint bottlenecks, errors, and dependencies in microservices, serverless, and containerized apps. They provide the \"how\" and \"where\" of system behavior, complementing metrics (overall health) and logs (individual events) by visualizing the request's full lifecycle, often as waterfall diagrams.",
    "WAF": "Web Application Firewall - a security tool that protects web applications by filtering, monitoring, and blocking malicious HTTP traffic before it reaches the server, acting as a shield against common web attacks like SQL injection, Cross-Site Scripting (XSS), and bots, operating at the application (Layer 7) level. It inspects incoming requests and applies rules to identify and stop threats that traditional firewalls miss, safeguarding sensitive data and application availability for businesses."
}


# keys_list = list(cardStack.keys())
keys_list = list(o11yStack.keys())
width = 50
session_active = True


def displayCard(card):
    print('\n')
    print(f" ------------------------------------------------ ")
    print(f"|                                                |")
    print(f"|                                                |")
    print(f"|                                                |")
    print(f"|                                                |")
    print(card.center(width))
    print(f"|                                                |")
    print(f"|                                                |")
    print(f"|                                                |")
    print(f"|                                                |")
    print(f" ------------------------------------------------ ")


def printAnswer(card):
    print(o11yStack[card])


while session_active:
    random_card = random.choice(keys_list)
    displayCard(random_card)
    input('Press Enter to flip the card')
    print('\n')
    printAnswer(random_card)
    print('\n')
    nextCard = input('Another card? (Y/N)')
    if nextCard.lower() == 'n':
        session_active = False
